In [18]:
import pandas as pd
import sqlite3

In [2]:
Hitters_Data = pd.read_csv("../CapstoneProject/HitterData.csv")

In [3]:
conn = sqlite3.connect("Baseball_Data.db")

In [4]:
Hitters_Data.to_sql('Hitters', conn)

/opt/tljh/user/lib/python3.6/site-packages/pandas/core/generic.py:2130: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

ValueError: Table 'Hitters' already exists.

In [7]:
sql_query = 'SELECT * FROM Hitters'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

      index             Player  Year  Age Team        Position  Games   AB  \
0         0         Sandy Leon  2013   24  WSH         Catcher      2    1
1         1         Sandy Leon  2014   25  WSH         Catcher     20   64
2         2         Sandy Leon  2015   26  BOS         Catcher     41  114
3         3         Sandy Leon  2016   27  BOS         Catcher     78  252
4         4         Sandy Leon  2017   28  BOS         Catcher     85  271
5         5         Sandy Leon  2018   29  BOS         Catcher     89  265
6         6  Christian Vazquez  2014   23  BOS         Catcher     55  175
7         7  Christian Vazquez  2016   25  BOS         Catcher     57  172
8         8  Christian Vazquez  2017   26  BOS         Catcher     99  324
9         9  Christian Vazquez  2018   27  BOS         Catcher     80  251
10       10    Xander Bogaerts  2013   20  BOS       Shortstop     18   44
11       11    Xander Bogaerts  2014   21  BOS       Shortstop    144  538
12       12    Xander Bogaerts  2015   22  BOS       Shortstop    156  613
13       13    Xander Bogaerts  2016   23  BOS       Shortstop    157  652
14       14    Xander Bogaerts  2017   24  BOS       Shortstop    148  571
15       15    Xander Bogaerts  2018   25  BOS       Shortstop    136  513
16       16      Rafael Devers  2017   20  BOS   Third Baseman     58  222
17       17      Rafael Devers  2018   21  BOS   Third Baseman    121  450
18       18     Mitch Moreland  2010   24  TEX   First Baseman     47  145
19       19     Mitch Moreland  2011   25  TEX   First Baseman    134  464
20       20     Mitch Moreland  2012   26  TEX   First Baseman    114  327
21       21     Mitch Moreland  2013   27  TEX   First Baseman    147  462
22       22     Mitch Moreland  2014   28  TEX   First Baseman     52  167
23       23     Mitch Moreland  2015   29  TEX   First Baseman    132  471
24       24     Mitch Moreland  2016   30  TEX   First Baseman    147  460
25       25     Mitch Moreland  2017   31  BOS   First Baseman    149  508
26       26     Mitch Moreland  2018   32  BOS   First Baseman    124  404
27       27      Eduardo Nunez  2010   23  NYY  Second Baseman     30   50
28       28      Eduardo Nunez  2011   24  NYY  Second Baseman    112  309
29       29      Eduardo Nunez  2012   25  NYY  Second Baseman     38   89
...     ...                ...   ...  ...  ...             ...    ...  ...
1867   1867      Evan Longoria  2017   31  TBR   Third Baseman    156  613
1868   1868      Evan Longoria  2018   32  SFG   Third Baseman    125  480
1869   1869          Joe Panik  2014   23  SFG  Second Baseman     73  269
1870   1870          Joe Panik  2015   24  SFG  Second Baseman    100  382
1871   1871          Joe Panik  2016   25  SFG  Second Baseman    127  464
1872   1872          Joe Panik  2017   26  SFG  Second Baseman    138  511
1873   1873          Joe Panik  2018   27  SFG  Second Baseman    102  358
1874   1874     Pablo Sandoval  2009   22  SFG   Third Baseman    153  572
1875   1875     Pablo Sandoval  2010   23  SFG   Third Baseman    152  563
1876   1876     Pablo Sandoval  2011   24  SFG   Third Baseman    117  426
1877   1877     Pablo Sandoval  2012   25  SFG   Third Baseman    108  396
1878   1878     Pablo Sandoval  2013   26  SFG   Third Baseman    141  525
1879   1879     Pablo Sandoval  2014   27  SFG   Third Baseman    157  588
1880   1880     Pablo Sandoval  2015   28  BOS   Third Baseman    126  470
1881   1881     Pablo Sandoval  2016   29  BOS   Third Baseman      3    6
1882   1882     Pablo Sandoval  2017   30  TOT   Third Baseman     79  259
1883   1883     Pablo Sandoval  2017   30  BOS   Third Baseman     32   99
1884   1884     Pablo Sandoval  2017   30  SFG   Third Baseman     47  160
1885   1885     Pablo Sandoval  2018   31  SFG   Third Baseman     92  230
1886   1886      Steven Duggar  2018   24  SFG      Outfielder     41  141
1887   1887       Kevin Pillar  2013   24  TOR      Outfielder     36  102
1888   1888       Kevin Pillar  2014   25  TOR      Outfielder     53  116
1889   1889       Kevin Pillar  2015   26  TOR      Outfielder    159  586
1890   1890       Kevin Pillar  2016   27  TOR      Outfielder    146  548
1891   1891       Kevin Pillar  2017   28  TOR      Outfielder    154  587
1892   1892       Kevin Pillar  2018   29  TOR      Outfielder    142  512
1893   1893     Mac Williamson  2015   24  SFG      Outfielder     10   32
1894   1894     Mac Williamson  2016   25  SFG      Outfielder     54  112
1895   1895     Mac Williamson  2017   26  SFG      Outfielder     28   68
1896   1896     Mac Williamson  2018   27  SFG      Outfielder     28   94

        R    H     ...          SB %  BB   SO        BA    OBP    SLG    OPS  \
0       0    0     ...      0.000000   0    1  0.000000  0.000  0.000  0.000
1       7   10     ...      0.000000   6   20  0.156250  0.229  0.219  0.448
2       8   21     ...      0.000000   7   28  0.184211  0.238  0.202  0.440
3      36   78     ...      0.000000  23   66  0.309524  0.369  0.476  0.845
4      32   61     ...      0.000000  25   74  0.225092  0.290  0.354  0.644
5      30   47     ...      1.000000  15   75  0.177358  0.232  0.279  0.511
6      15   42     ...      0.000000  19   33  0.240000  0.308  0.309  0.617
7      21   39     ...      0.000000  10   39  0.226744  0.277  0.404  0.681
8      43   94     ...      0.777778  17   64  0.290123  0.330  0.283  0.613
9      24   52     ...      0.800000  13   41  0.207171  0.257  0.485  0.742
10      7   11     ...      1.000000   5   13  0.250000  0.320  0.364  0.684
11     60  129     ...      0.400000  39  138  0.239777  0.297  0.362  0.659
12     84  196     ...      0.833333  32  101  0.319739  0.355  0.421  0.776
13    115  192     ...      0.764706  58  123  0.294479  0.356  0.446  0.802
14     94  156     ...      0.937500  56  116  0.273205  0.343  0.403  0.746
15     72  148     ...      0.800000  55  102  0.288499  0.360  0.522  0.882
16     34   63     ...      0.750000  18   57  0.283784  0.338  0.482  0.820
17     59  108     ...      0.714286  38  121  0.240000  0.298  0.433  0.731
18     20   37     ...      0.750000  25   36  0.255172  0.364  0.469  0.833
19     60  120     ...      0.500000  39   92  0.258621  0.320  0.414  0.734
20     41   90     ...      0.500000  23   71  0.275229  0.321  0.468  0.789
21     60  107     ...      0.000000  45  117  0.231602  0.299  0.437  0.736
22     18   41     ...      0.000000  12   43  0.245509  0.297  0.347  0.644
23     51  131     ...      1.000000  32  112  0.278132  0.330  0.482  0.812
24     49  107     ...      1.000000  35  118  0.232609  0.298  0.422  0.720
25     73  125     ...      0.000000  57  120  0.246063  0.326  0.443  0.769
26     57   99     ...      1.000000  50  102  0.245050  0.325  0.433  0.758
27     12   14     ...      1.000000   3    2  0.280000  0.321  0.360  0.681
28     38   82     ...      0.785714  22   37  0.265372  0.313  0.385  0.698
29     14   26     ...      0.846154   6   12  0.292135  0.330  0.393  0.723
...   ...  ...     ...           ...  ..  ...       ...    ...    ...    ...
1867   71  160     ...      0.857143  46  109  0.261011  0.313  0.424  0.737
1868   51  117     ...      0.750000  22  101  0.243750  0.281  0.413  0.694
1869   31   82     ...      0.000000  16   33  0.304833  0.343  0.368  0.711
1870   59  119     ...      0.600000  38   42  0.311518  0.378  0.455  0.833
1871   67  111     ...      1.000000  50   47  0.239224  0.315  0.379  0.694
1872   60  147     ...      0.800000  46   54  0.287671  0.347  0.421  0.768
1873   38   91     ...      0.666667  26   30  0.254190  0.307  0.332  0.639
1874   79  189     ...      0.500000  52   83  0.330420  0.387  0.556  0.943
1875   61  151     ...      0.600000  47   81  0.268206  0.323  0.409  0.732
1876   55  134     ...      0.333333  32   63  0.314554  0.357  0.552  0.909
1877   59  112     ...      0.500000  38   59  0.282828  0.342  0.447  0.789
1878   52  146     ...      0.000000  47   79  0.278095  0.341  0.417  0.758
1879   68  164     ...      0.000000  39   85  0.278912  0.324  0.415  0.739
1880   43  115     ...      0.000000  25   73  0.244681  0.292  0.366  0.658
1881    0    0     ...      0.000000   1    4  0.000000  0.143  0.000  0.143
1882   27   57     ...      0.000000  16   53  0.220077  0.265  0.367  0.632
1883   10   21     ...      0.000000   8   24  0.212121  0.269  0.354  0.623
1884   17   36     ...      0.000000   8   29  0.225000  0.263  0.375  0.638
1885   22   57     ...      0.000000  19   52  0.247826  0.310  0.417  0.727
1886   20   36     ...      0.833333  10   44  0.255319  0.303  0.390  0.693
1887   11   21     ...      0.000000   4   29  0.205882  0.250  0.333  0.583
1888   19   31     ...      0.333333   4   28  0.267241  0.295  0.397  0.692
1889   76  163     ...      0.862069  28   85  0.278157  0.314  0.399  0.713
1890   59  146     ...      0.700000  24   90  0.266423  0.303  0.376  0.679
1891   72  150     ...      0.714286  33   95  0.255537  0.300  0.404  0.704
1892   65  129     ...      0.823529  18   98  0.251953  0.282  0.426  0.708
1893    2    7     ...      0.000000   0    8  0.218750  0.235  0.281  0.516
1894   14   25     ...      0.000000  13   35  0.223214  0.315  0.411  0.726
1895    8   16     ...      0.500000   5   25  0.235294  0.288  0.397  0.685
1896   14   20     ...      0.500000  11   27  0.212766  0.295  0.383  0.678

      WAR    Salary  Adj Salary
0     0.0     80327      100961
1     0.1    243655      282122
2    -0.3    393259      442126
3     2.8    534000      554575
4     0.7   1300000     1286637
5    -0.4   1950000     1950000
6     1.0    224043      259414
7    -0.3    339163      352231
8     1.1    561000      555234
9    -0.8   1425000     1425000
10    0.3    112549      141460
11    0.1    517000      598622
12    4.5    543000      610474
13    3.8    650500      675564
14    2.2   4500000     4453745
15    3.8   7050000     7050000
16    1.3    535000      529501
17    0.0    564500      564500
18    0.9    400000      612334
19    0.0    426000      585914
20    0.5    491100      635081
21    0.6    502700      631831
22   -0.2   2650000     3068370
23    2.3   2950000     3316573
24    0.7   5700000     5919625
25    1.9   5500000     5443466
26    0.9   6500000     6500000
27    0.0    400000      612334
28   -0.4    419300      576699
29    0.4    523800      677368
...   ...       ...         ...
1867  3.4  11525000    11406536
1868  2.0  14000000    14000000
1869  1.2    273224      316359
1870  3.3    522500      587427
1871  1.3    545000      565999
1872  1.2    600000      593833
1873 -0.1   3450000     3450000
1874  4.3    401750      633609
1875  1.5    465000      711838
1876  6.0    500000      687693
1877  2.2   3200000     4138180
1878  2.3   5700000     7164187
1879  3.4   8250000     9552473
1880 -0.9  20000000    22485242
1881 -0.2  17000000    17655021
1882 -1.4  17169534    16993051
1883 -1.0  17000000    16825259
1884 -0.4    169534      167791
1885  0.1  18000000    18000000
1886  1.1    249050      249050
1887  0.1    125846      158173
1888  0.7    174863      202470
1889  4.9    512000      575622
1890  3.5    521100      541178
1891  3.0    555000      549295
1892  2.5   3250000     3250000
1893 -0.3     49918       56121
1894  0.5    507500      527054
1895 -0.2    203205      201116
1896  0.5    187520      187520

[1897 rows x 26 columns]

In [64]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "Catcher" AND Year > 2015 AND "Adj Salary" < 4000000 AND WAR > 2'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index             Player  Year  Age Team Position  Games   AB   R    H  \
0       3         Sandy Leon  2016   27  BOS  Catcher     78  252  36   78
1      83       Gary Sanchez  2016   23  NYY  Catcher     53  201  34   60
2      84       Gary Sanchez  2017   24  NYY  Catcher    122  471  79  131
3     478     Salvador Perez  2017   27  KCR  Catcher    129  471  57  126
4     522  Robinson Chirinos  2017   33  TEX  Catcher     88  263  46   67
5     777    Jonathan Lucroy  2016   30  MIL  Catcher     95  338  48  101
6     870        JT Realmuto  2016   25  MIA  Catcher    137  509  60  154
7     871        JT Realmuto  2017   26  MIA  Catcher    141  532  68  148
8     872        JT Realmuto  2018   27  MIA  Catcher    125  477  74  132
9    1120        Kurt Suzuki  2017   33  ATL  Catcher     81  276  38   78
10   1121        Kurt Suzuki  2018   34  ATL  Catcher    105  347  45   94
11   1256  Willson Contreras  2017   25  CHC  Catcher    117  377  50  104
12   1257  Willson Contreras  2018   26  CHC  Catcher    138  474  50  118
13   1308    Yasmani Grandal  2016   27  LAD  Catcher    126  390  49   89
14   1494    Tucker Barnhart  2017   26  CIN  Catcher    121  370  26  100
15   1549      Austin Barnes  2017   27  LAD  Catcher    102  218  35   63
16   1620         Alex Avila  2017   30  TOT  Catcher    112  311  41   82
17   1626       Carson Kelly  2018   23  STL  Catcher     19   35   1    4
18   1833       Stephen Vogt  2016   31  OAK  Catcher    137  490  54  123

       ...          SB %  BB   SO        BA    OBP    SLG    OPS  WAR  \
0      ...      0.000000  23   66  0.309524  0.369  0.476  0.845  2.8
1      ...      1.000000  24   57  0.298507  0.376  0.657  1.033  3.0
2      ...      0.666667  40  120  0.278132  0.345  0.531  0.876  4.1
3      ...      1.000000  17   95  0.267516  0.297  0.495  0.792  2.5
4      ...      1.000000  34   79  0.254753  0.360  0.506  0.866  2.6
5      ...      1.000000  33   70  0.298817  0.359  0.482  0.841  2.3
6      ...      0.750000  28  100  0.302554  0.343  0.428  0.771  2.6
7      ...      0.800000  36  106  0.278195  0.332  0.451  0.783  3.9
8      ...      0.600000  38  104  0.276730  0.340  0.484  0.824  4.3
9      ...      0.000000  17   39  0.282609  0.351  0.536  0.887  2.7
10     ...      0.000000  22   43  0.270893  0.332  0.444  0.776  2.1
11     ...      0.555556  45   98  0.275862  0.356  0.499  0.855  3.9
12     ...      0.800000  53  121  0.248945  0.339  0.390  0.729  2.8
13     ...      0.250000  64  116  0.228205  0.339  0.477  0.816  2.7
14     ...      1.000000  42   68  0.270270  0.347  0.403  0.750  3.3
15     ...      0.800000  39   43  0.288991  0.408  0.486  0.894  2.6
16     ...      0.000000  62  120  0.263666  0.387  0.447  0.834  2.1
17     ...      0.000000   3    7  0.114286  0.205  0.114  0.319  5.0
18     ...      0.000000  56   83  0.251020  0.305  0.406  0.711  3.7

     Salary  Adj Salary
0    534000      554575
1    171926      178550
2    557900      552165
3   3000000     2969163
4   1900000     1880470
5   2786886     2894267
6    532500      553018
7    562500      556718
8   2900000     2900000
9   1600000     1583554
10  3850000     3850000
11   544500      538903
12   604500      604500
13  2800000     2907886
14   575000      569090
15   540000      534449
16  2000000     1979442
17   175800      175800
18   527500      547825

[19 rows x 26 columns]

In [45]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "First Baseman" AND Year > 2015 AND "Adj Salary" < 3500000 AND Games < 80'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index            Player  Year  Age Team       Position  Games   AB   R  \
0      47      Steve Pearce  2016   33  TBR  First Baseman     60  204  26
1      48      Steve Pearce  2016   33  BAL  First Baseman     25   60   9
2      52      Steve Pearce  2018   35  BOS  First Baseman     50  136  19
3      97         Luke Voit  2017   26  NYY  First Baseman     62  114  18
4      98         Luke Voit  2018   27  NYY  First Baseman     47  143  30
5     145       Ji-Man Choi  2016   25  LAA  First Baseman     54  112   9
6     146       Ji-Man Choi  2017   26  NYY  First Baseman      6   15   2
7     147       Ji-Man Choi  2018   27  TOT  First Baseman     61  190  25
8     148       Ji-Man Choi  2018   27  MIL  First Baseman     12   30   4
9     149       Ji-Man Choi  2018   27  TBR  First Baseman     49  160  21
10    201          Rio Ruiz  2016   22  ATL  First Baseman      5    7   1
11    202          Rio Ruiz  2017   23  ATL  First Baseman     53  150  22
12    203          Rio Ruiz  2018   24  ATL  First Baseman     14   12   1
13    333     Yonder Alonso  2017   30  SEA  First Baseman     42  132  20
14    546       Tyler White  2017   26  HOU  First Baseman     22   61   7
15    547       Tyler White  2018   27  HOU  First Baseman     66  210  27
16    687        Ryon Healy  2016   24  OAK  First Baseman     72  269  36
17    690  Daniel Vogelbach  2016   23  SEA  First Baseman      8   12   0
18    691  Daniel Vogelbach  2017   24  SEA  First Baseman     16   28   0
19    692  Daniel Vogelbach  2018   25  SEA  First Baseman     37   87   9
20    830        Matt Olson  2016   22  OAK  First Baseman     11   21   3
21    831        Matt Olson  2017   23  OAK  First Baseman     59  189  33
22    891      Rhys Hoskins  2017   24  PHI  First Baseman     50  170  37
23   1069     Dominic Smith  2017   22  NYM  First Baseman     49  167  17
24   1070     Dominic Smith  2018   23  NYM  First Baseman     56  143  14
25   1381         Josh Bell  2016   23  PIT  First Baseman     45  128  18
26   1578         Max Muncy  2016   25  OAK  First Baseman     51  113  13
27   1659  Christian Walker  2017   26  ARI  First Baseman     11   12   2
28   1660  Christian Walker  2018   27  ARI  First Baseman     37   49   6
29   1769      Ryan McMahon  2017   22  COL  First Baseman     17   19   2
30   1837      Tyler Austin  2016   24  NYY  First Baseman     31   83   7
31   1838      Tyler Austin  2017   25  NYY  First Baseman     20   40   4
32   1839      Tyler Austin  2018   26  TOT  First Baseman     69  244  34
33   1840      Tyler Austin  2018   26  NYY  First Baseman     34  121  16
34   1841      Tyler Austin  2018   26  MIN  First Baseman     35  123  18

     H     ...          SB %  BB  SO        BA    OBP    SLG    OPS  WAR  \
0   63     ...      0.000000  26  40  0.308824  0.388  0.520  0.908  2.2
1   13     ...      0.000000   8  14  0.216667  0.329  0.400  0.729  0.1
2   38     ...      0.000000  22  27  0.279412  0.394  0.507  0.901  1.2
3   28     ...      0.000000   7  31  0.245614  0.306  0.430  0.736  0.3
4   46     ...      0.000000  17  43  0.321678  0.398  0.671  1.069  1.4
5   19     ...      0.333333  16  27  0.169643  0.271  0.339  0.610 -0.6
6    4     ...      0.000000   2   5  0.266667  0.333  0.733  1.066  0.2
7   50     ...      1.000000  26  55  0.263158  0.357  0.505  0.862  1.1
8    7     ...      0.000000   2  14  0.233333  0.281  0.500  0.781  0.1
9   43     ...      1.000000  24  41  0.268750  0.370  0.506  0.876  1.0
10   2     ...      1.000000   0   2  0.285714  0.286  0.571  0.857  0.1
11  29     ...      1.000000  19  41  0.193333  0.283  0.307  0.590 -0.4
12   1     ...      0.000000   2   5  0.083333  0.267  0.083  0.350  0.0
13  35     ...      1.000000  18  30  0.265152  0.353  0.439  0.792  0.5
14  17     ...      0.000000   4  16  0.278689  0.328  0.525  0.853  0.1
15  58     ...      0.000000  24  49  0.276190  0.354  0.533  0.887  1.6
16  82     ...      0.000000  12  60  0.304833  0.337  0.524  0.861  2.1
17   1     ...      0.000000   1   6  0.083333  0.154  0.083  0.237 -0.3
18   6     ...      0.000000   3   9  0.214286  0.290  0.250  0.540 -0.5
19  18     ...      0.000000  13  26  0.206897  0.324  0.368  0.692  0.2
20   2     ...      0.000000   7   4  0.095238  0.321  0.143  0.464 -0.2
21  49     ...      0.000000  22  60  0.259259  0.352  0.651  1.003  2.8
22  44     ...      1.000000  37  46  0.258824  0.396  0.618  1.014  2.0
23  33     ...      0.000000  14  49  0.197605  0.262  0.395  0.657 -1.1
24  32     ...      0.000000   4  47  0.223776  0.255  0.420  0.675 -0.6
25  35     ...      0.000000  21  19  0.273438  0.368  0.406  0.774 -0.5
26  21     ...      0.000000  20  24  0.185841  0.308  0.257  0.565 -0.2
27   3     ...      0.000000   1   5  0.250000  0.400  0.833  1.233  0.1
28   8     ...      1.000000   3  22  0.163265  0.226  0.388  0.614 -0.2
29   3     ...      0.000000   5   5  0.157895  0.333  0.211  0.544 -0.1
30  20     ...      1.000000   7  36  0.240964  0.300  0.458  0.758 -0.1
31   9     ...      0.000000   4  17  0.225000  0.283  0.425  0.708 -0.2
32  56     ...      0.333333  19  95  0.229508  0.287  0.480  0.767  0.5
33  27     ...      0.500000   8  53  0.223140  0.280  0.471  0.751  0.2
34  29     ...      0.000000  11  42  0.235772  0.294  0.488  0.782  0.3

     Salary  Adj Salary
0   3364755     3494401
1   1635245     1698252
2   1500000     1500000
3    271839      269045
4    164080      164080
5    323232      335686
6    700000      692805
7    466140      466140
8     86830       86830
9    379310      379310
10    44368       46078
11   295223      292188
12    77854       77854
13  1245906     1233100
14   134458      133076
15   278350      278350
16   507500      527054
17    58233       60477
18   111074      109932
19   228852      228852
20    58233       60477
21   236763      234329
22   154919      153327
23   151996      150434
24   219750      219750
25   146969      152632
26   507500      527054
27    64306       63645
28   193380      193380
29   111074      109932
30   130000      135009
31   141423      139969
32   420420      420420
33   234234      234234
34   186186      186186

[35 rows x 26 columns]

In [29]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "Second Baseman" AND Year > 2015 AND WAR > 2'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index            Player  Year  Age Team        Position  Games   AB    R  \
0      33     Eduardo Nunez  2016   29  TOT  Second Baseman    141  553   73
1      96    Gleyber Torres  2018   21  NYY  Second Baseman    123  431   54
2     156  Daniel Robertson  2018   24  TBR  Second Baseman     87  282   46
3     271      Jason Kipnis  2016   29  CLE  Second Baseman    156  610   91
4     346    Yolmer Sanchez  2017   25  CHW  Second Baseman    141  484   63
5     347    Yolmer Sanchez  2018   26  CHW  Second Baseman    155  600   62
6     441   Jonathan Schoop  2016   24  BAL  Second Baseman    162  615   82
7     442   Jonathan Schoop  2017   25  BAL  Second Baseman    160  622   92
8     483   Whit Merrifield  2017   28  KCR  Second Baseman    145  587   80
9     484   Whit Merrifield  2018   29  KCR  Second Baseman    158  632   88
10    531      Aledmys Diaz  2016   25  STL  Second Baseman    111  404   71
11    539       Jose Altuve  2016   26  HOU  Second Baseman    161  640  108
12    540       Jose Altuve  2017   27  HOU  Second Baseman    153  590  112
13    541       Jose Altuve  2018   28  HOU  Second Baseman    137  534   84
14    616    Logan Forsythe  2016   29  TBR  Second Baseman    127  511   76
15    624      Rougned Odor  2016   22  TEX  Second Baseman    150  605   89
16    626      Rougned Odor  2018   24  TEX  Second Baseman    129  474   76
17    685        Dee Gordon  2017   29  MIA  Second Baseman    158  653  114
18    837  Jurickson Profar  2018   25  TEX  Second Baseman    146  524   82
19    888   Cesar Hernandez  2016   26  PHI  Second Baseman    155  547   67
20    889   Cesar Hernandez  2017   27  PHI  Second Baseman    128  511   85
21    961      Ozzie Albies  2018   21  ATL  Second Baseman    158  639  105
22   1039     Robinson Cano  2016   33  SEA  Second Baseman    161  655  107
23   1040     Robinson Cano  2017   34  SEA  Second Baseman    150  592   79
24   1041     Robinson Cano  2018   35  SEA  Second Baseman     80  310   44
25   1066       Jeff McNeil  2018   26  NYM  Second Baseman     63  225   35
26   1126      Brian Dozier  2016   29  MIN  Second Baseman    155  615  104
27   1127      Brian Dozier  2017   30  MIN  Second Baseman    152  617  106
28   1227       Neil Walker  2016   30  NYM  Second Baseman    113  412   57
29   1260       Javier Baez  2016   23  CHC  Second Baseman    142  421   50
30   1261       Javier Baez  2017   24  CHC  Second Baseman    145  469   75
31   1262       Javier Baez  2018   25  CHC  Second Baseman    160  606  101
32   1386      Adam Frazier  2018   26  PIT  Second Baseman    113  318   52
33   1460       Jedd Gyorko  2016   27  STL  Second Baseman    128  400   58
34   1461       Jedd Gyorko  2017   28  STL  Second Baseman    125  426   52
35   1469       Kolten Wong  2018   27  STL  Second Baseman    127  353   41
36   1506    Derek Dietrich  2016   26  MIA  Second Baseman    128  351   39
37   1718       Ian Kinsler  2016   34  DET  Second Baseman    153  618  117
38   1719       Ian Kinsler  2017   35  DET  Second Baseman    139  551   90
39   1720       Ian Kinsler  2018   36  TOT  Second Baseman    128  487   66
40   1721       Ian Kinsler  2018   36  LAA  Second Baseman     91  355   49
41   1777     Daniel Murphy  2016   31  WSN  Second Baseman    142  531   88
42   1778     Daniel Murphy  2017   32  WSN  Second Baseman    144  534   94

      H     ...          SB %  BB   SO        BA    OBP    SLG    OPS  WAR  \
0   159     ...      0.800000  29   88  0.287523  0.325  0.432  0.757  2.5
1   117     ...      0.750000  42  122  0.271462  0.340  0.480  0.820  2.9
2    74     ...      0.500000  43   77  0.262411  0.382  0.415  0.797  2.6
3   168     ...      0.833333  60  146  0.275410  0.343  0.469  0.812  4.2
4   129     ...      0.470588  35  111  0.266529  0.319  0.413  0.732  3.5
5   145     ...      0.700000  49  138  0.241667  0.306  0.372  0.678  2.6
6   164     ...      0.333333  21  137  0.266667  0.298  0.454  0.752  2.4
7   182     ...      1.000000  35  142  0.292605  0.338  0.503  0.841  5.2
8   169     ...      0.809524  29   88  0.287905  0.324  0.460  0.784  3.9
9   192     ...      0.818182  61  114  0.303797  0.367  0.438  0.805  5.5
10  121     ...      0.500000  41   60  0.299505  0.369  0.510  0.879  3.5
11  216     ...      0.750000  60   70  0.337500  0.396  0.531  0.927  7.7
12  204     ...      0.842105  58   84  0.345763  0.410  0.547  0.957  8.1
13  169     ...      0.809524  55   79  0.316479  0.386  0.451  0.837  5.2
14  135     ...      0.500000  46  127  0.264188  0.333  0.444  0.777  3.4
15  164     ...      0.666667  19  135  0.271074  0.296  0.502  0.798  2.5
16  120     ...      0.500000  43  127  0.253165  0.326  0.424  0.750  2.7
17  201     ...      0.789474  25   93  0.307810  0.341  0.375  0.716  3.4
18  133     ...      1.000000  54   88  0.253817  0.335  0.458  0.793  2.1
19  161     ...      0.566667  66  116  0.294333  0.371  0.393  0.764  3.2
20  150     ...      0.750000  61  104  0.293542  0.373  0.421  0.794  3.0
21  167     ...      0.875000  36  116  0.261346  0.305  0.452  0.757  3.8
22  195     ...      0.000000  47  100  0.297710  0.350  0.533  0.883  7.3
23  166     ...      1.000000  49   85  0.280405  0.338  0.453  0.791  3.5
24   94     ...      0.000000  32   47  0.303226  0.374  0.471  0.845  3.2
25   74     ...      0.875000  14   24  0.328889  0.381  0.471  0.852  2.4
26  165     ...      0.900000  61  138  0.268293  0.340  0.546  0.886  6.3
27  167     ...      0.695652  78  141  0.270665  0.359  0.498  0.857  4.4
28  116     ...      0.750000  42   84  0.281553  0.347  0.476  0.823  2.6
29  115     ...      0.800000  15  108  0.273159  0.314  0.423  0.737  3.2
30  128     ...      0.769231  30  144  0.272921  0.317  0.480  0.797  2.8
31  176     ...      0.700000  29  167  0.290429  0.326  0.554  0.880  6.3
32   88     ...      0.250000  29   53  0.276730  0.342  0.456  0.798  2.7
33   97     ...      0.000000  37   96  0.242500  0.306  0.495  0.801  3.0
34  116     ...      0.750000  47  105  0.272300  0.341  0.472  0.813  3.7
35   88     ...      0.545455  31   60  0.249292  0.332  0.388  0.720  3.5
36   98     ...      1.000000  32   84  0.279202  0.374  0.425  0.799  2.4
37  178     ...      0.700000  45  115  0.288026  0.348  0.484  0.832  6.0
38  130     ...      0.736842  55   86  0.235935  0.313  0.412  0.725  2.3
39  117     ...      0.695652  40   64  0.240246  0.301  0.380  0.681  2.4
40   85     ...      0.692308  30   40  0.239437  0.304  0.406  0.710  2.5
41  184     ...      0.625000  35   57  0.346516  0.390  0.595  0.985  4.5
42  172     ...      1.000000  52   77  0.322097  0.384  0.543  0.927  2.8

      Salary  Adj Salary
0    1475000     1531833
1     474660      474660
2     548300      548300
3    6000000     6231184
4     546000      540388
5    2350000     2350000
6     522500      542632
7    3475000     3439281
8     543750      538161
9     569500      569500
10   2000000     2077061
11   3525000     3660821
12   4500000     4453745
13  17000000    17000000
14   4000000     4154123
15    522700      542840
16   3000000     3000000
17   7500000     7422909
18   1050000     1050000
19    525000      545229
20   2550000     2523789
21    555000      555000
22  24050000    24976662
23  24000000    23753308
24  13677440    13677440
25    202170      202170
26   3000000     3115592
27   6025000     5963070
28  10550000    10956499
29    521000      541074
30    609000      602740
31    657000      657000
32    211830      211830
33   4000000     4154123
34   4500000     4453745
35   4000000     4000000
36    522500      542632
37  14000000    14539429
38  11000000    10886933
39  11000000    11000000
40   9166660     9166660
41   8000000     8308245
42  12000000    11876654

[43 rows x 26 columns]

In [30]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "Shortstop" AND Year > 2015 AND WAR > 2'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index             Player  Year  Age Team   Position  Games   AB    R    H  \
0      13    Xander Bogaerts  2016   23  BOS  Shortstop    157  652  115  192
1      14    Xander Bogaerts  2017   24  BOS  Shortstop    148  571   94  156
2      15    Xander Bogaerts  2018   25  BOS  Shortstop    136  513   72  148
3     232      Freddy Galvis  2018   28  SDP  Shortstop    162  602   62  149
4     275   Francisco Lindor  2016   22  CLE  Shortstop    158  604   99  182
5     276   Francisco Lindor  2017   23  CLE  Shortstop    159  651   99  178
6     277   Francisco Lindor  2018   24  CLE  Shortstop    158  661  129  183
7     335       Tim Anderson  2016   23  CHW  Shortstop     99  410   57  116
8     337       Tim Anderson  2018   25  CHW  Shortstop    153  567   77  136
9     427    Marwin Gonzalez  2017   28  HOU  Shortstop    134  455   67  138
10    428    Marwin Gonzalez  2018   29  HOU  Shortstop    145  489   61  121
11    432      Jorge Polanco  2017   23  MIN  Shortstop    133  488   60  125
12    487  Adalberto Mondesi  2018   22  KCR  Shortstop     75  275   47   76
13    528      Carlos Correa  2016   21  HOU  Shortstop    153  577   76  158
14    529      Carlos Correa  2017   22  HOU  Shortstop    109  422   82  133
15    606   Asdrubal Cabrera  2016   30  NYM  Shortstop    141  521   65  146
16    673        Tim Beckham  2017   27  TOT  Shortstop    137  533   67  148
17    675        Tim Beckham  2017   27  BAL  Shortstop     50  216   36   66
18    767  Andrelton Simmons  2016   26  LAA  Shortstop    124  448   48  126
19    768  Andrelton Simmons  2017   27  LAA  Shortstop    158  589   77  164
20    769  Andrelton Simmons  2018   28  LAA  Shortstop    146  554   68  162
21    841      Marcus Semien  2016   25  OAK  Shortstop    159  568   72  135
22    843      Marcus Semien  2018   27  OAK  Shortstop    159  632   89  161
23    909        Jean Segura  2016   26  ARI  Shortstop    153  637  102  203
24    910        Jean Segura  2017   27  SEA  Shortstop    125  524   80  157
25    911        Jean Segura  2018   28  SEA  Shortstop    144  586   91  178
26    985     Dansby Swanson  2018   24  ATL  Shortstop    136  478   51  114
27   1155        Trea Turner  2016   23  WSN  Shortstop     73  307   53  105
28   1156        Trea Turner  2017   24  WSN  Shortstop     98  412   75  117
29   1157        Trea Turner  2018   25  WSN  Shortstop    162  664  103  180
30   1201     Starlin Castro  2018   28  MIA  Shortstop    154  593   76  165
31   1219       Miguel Rojas  2017   28  MIA  Shortstop     90  272   37   79
32   1220       Miguel Rojas  2018   29  MIA  Shortstop    153  488   44  123
33   1286    Addison Russell  2016   22  CHC  Shortstop    151  525   67  125
34   1287    Addison Russell  2017   23  CHC  Shortstop    110  352   52   84
35   1316      Orlando Arcia  2017   22  MIL  Shortstop    153  506   56  140
36   1447        Paul Dejong  2017   23  STL  Shortstop    108  417   55  119
37   1448        Paul Dejong  2018   24  STL  Shortstop    115  436   68  105
38   1517      Jose Iglesias  2018   28  DET  Shortstop    125  432   43  116
39   1521        Jose Peraza  2018   24  CIN  Shortstop    157  632   85  182
40   1581       Corey Seager  2016   22  LAD  Shortstop    157  627  105  193
41   1582       Corey Seager  2017   23  LAD  Shortstop    145  539   85  159
42   1637         Nick Ahmed  2018   28  ARI  Shortstop    153  516   61  121
43   1657        Ketel Marte  2018   24  ARI  Shortstop    153  520   68  135
44   1796       Trevor Story  2016   23  COL  Shortstop     97  372   67  101
45   1797       Trevor Story  2017   24  COL  Shortstop    145  503   68  120
46   1798       Trevor Story  2018   25  COL  Shortstop    157  598   88  174
47   1855   Brandon Crawford  2016   29  SFG  Shortstop    155  553   67  152
48   1857   Brandon Crawford  2018   31  SFG  Shortstop    151  531   63  135

       ...          SB %  BB   SO        BA    OBP    SLG    OPS  WAR  \
0      ...      0.764706  58  123  0.294479  0.356  0.446  0.802  3.8
1      ...      0.937500  56  116  0.273205  0.343  0.403  0.746  2.2
2      ...      0.800000  55  102  0.288499  0.360  0.522  0.882  3.8
3      ...      0.571429  45  147  0.247508  0.299  0.380  0.679  2.3
4      ...      0.791667  57   88  0.301325  0.358  0.435  0.793  5.9
5      ...      0.833333  60   93  0.273425  0.337  0.505  0.842  5.5
6      ...      0.714286  70  107  0.276853  0.352  0.519  0.871  7.9
7      ...      0.833333  13  117  0.282927  0.306  0.432  0.738  2.7
8      ...      0.764706  30  149  0.239859  0.281  0.406  0.687  2.5
9      ...      0.727273  49   99  0.303297  0.377  0.530  0.907  4.1
10     ...      0.400000  53  126  0.247444  0.324  0.409  0.733  2.5
11     ...      0.722222  41   78  0.256148  0.313  0.410  0.723  2.1
12     ...      0.820513  11   77  0.276364  0.306  0.498  0.804  3.1
13     ...      0.812500  75  139  0.273830  0.361  0.451  0.812  6.1
14     ...      0.666667  53   92  0.315166  0.391  0.550  0.941  6.1
15     ...      0.833333  38  103  0.280230  0.336  0.474  0.810  2.8
16     ...      0.545455  36  167  0.277674  0.328  0.454  0.782  3.3
17     ...      0.500000  12   57  0.305556  0.348  0.523  0.871  2.1
18     ...      0.909091  28   38  0.281250  0.324  0.366  0.690  4.2
19     ...      0.760000  47   67  0.278438  0.331  0.421  0.752  7.0
20     ...      0.833333  35   44  0.292419  0.337  0.417  0.754  6.2
21     ...      0.833333  51  139  0.237676  0.300  0.435  0.735  2.8
22     ...      0.700000  61  131  0.254747  0.318  0.388  0.706  4.3
23     ...      0.767442  39  101  0.318681  0.368  0.499  0.867  5.5
24     ...      0.733333  34   83  0.299618  0.349  0.427  0.776  3.3
25     ...      0.645161  32   69  0.303754  0.341  0.415  0.756  4.3
26     ...      0.714286  44  122  0.238494  0.304  0.395  0.699  2.3
27     ...      0.846154  14   59  0.342020  0.370  0.567  0.937  3.4
28     ...      0.851852  30   80  0.283981  0.338  0.451  0.789  2.6
29     ...      0.826923  69  132  0.271084  0.344  0.416  0.760  4.1
30     ...      0.600000  48  124  0.278246  0.329  0.400  0.729  3.3
31     ...      0.666667  27   32  0.290441  0.361  0.375  0.736  2.2
32     ...      0.666667  24   69  0.252049  0.297  0.346  0.643  2.4
33     ...      0.833333  55  135  0.238095  0.321  0.417  0.738  4.1
34     ...      0.666667  29   91  0.238636  0.304  0.418  0.722  2.4
35     ...      0.666667  36  100  0.276680  0.324  0.407  0.731  2.5
36     ...      1.000000  21  124  0.285372  0.325  0.532  0.857  2.7
37     ...      0.500000  36  123  0.240826  0.313  0.433  0.746  3.8
38     ...      0.714286  19   47  0.268519  0.310  0.389  0.699  2.2
39     ...      0.793103  29   75  0.287975  0.326  0.416  0.742  2.3
40     ...      0.500000  54  133  0.307815  0.365  0.512  0.877  5.9
41     ...      0.666667  67  131  0.294991  0.375  0.479  0.854  5.7
42     ...      0.555556  40  109  0.234496  0.290  0.411  0.701  3.2
43     ...      0.857143  54   79  0.259615  0.332  0.437  0.769  3.3
44     ...      0.615385  35  130  0.271505  0.341  0.567  0.908  3.2
45     ...      0.777778  49  191  0.238569  0.308  0.457  0.765  2.5
46     ...      0.818182  47  168  0.290970  0.348  0.567  0.915  5.6
47     ...      1.000000  57  115  0.274864  0.342  0.430  0.772  4.9
48     ...      0.444444  50  122  0.254237  0.325  0.394  0.719  2.5

      Salary  Adj Salary
0     650500      675564
1    4500000     4453745
2    7050000     7050000
3    6825000     6825000
4     540300      561118
5     579300      573345
6     623200      623200
7     507500      527054
8    1000000     1000000
9    3725000     3686711
10   5125000     5125000
11    540000      534449
12    310580      310580
13    516700      536609
14    535000      529501
15   8250000     8567878
16    885000      875903
17    304668      301536
18   6000000     6231184
19   8000000     7917769
20  11000000    11000000
21    512500      532247
22   3125000     3125000
23   2600000     2700180
24   9200000     9105435
25   9000000     9000000
26    565000      565000
27    507500      527054
28    554900      549196
29    577200      577200
30  10000000    10000000
31    535000      529501
32   1180000     1180000
33    527000      547306
34    644000      637380
35    538100      532569
36    535000      529501
37   2000000     2000000
38   6275000     6275000
39    570000      570000
40    510000      529651
41    575000      569090
42   1275000     1275000
43   3000000     3000000
44    507500      527054
45    540000      534449
46    555000      555000
47   7000000     7269715
48  15000000    15000000

[49 rows x 26 columns]

In [34]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "Third Baseman" AND Year > 2015 AND WAR > 2 AND Salary > 1000000'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index             Player  Year  Age Team       Position  Games   AB    R  \
0      90        DJ Lemahieu  2016   27  COL  Third Baseman    146  552  104
1      91        DJ Lemahieu  2017   28  COL  Third Baseman    155  609   95
2      92        DJ Lemahieu  2018   29  COL  Third Baseman    128  533   90
3     209    Jonathan Villar  2018   27  TOT  Third Baseman    141  466   54
4     281       Jose Ramirez  2017   24  CLE  Third Baseman    152  585  107
5     282       Jose Ramirez  2018   25  CLE  Third Baseman    157  578  110
6     392      Josh Harrison  2017   29  PIT  Third Baseman    128  486   66
7     705  Edwin Encarnacion  2016   33  TOR  Third Baseman    160  601   99
8     706  Edwin Encarnacion  2017   34  CLE  Third Baseman    157  554   96
9     969     Josh Donaldson  2016   30  TOR  Third Baseman    155  577  122
10    970     Josh Donaldson  2017   31  TOR  Third Baseman    113  415   65
11   1049       Todd Frazier  2016   30  CHW  Third Baseman    158  590   89
12   1050       Todd Frazier  2017   31  TOT  Third Baseman    147  474   74
13   1149     Anthony Rendon  2016   26  WSN  Third Baseman    156  567   91
14   1150     Anthony Rendon  2017   27  WSN  Third Baseman    147  508   81
15   1151     Anthony Rendon  2018   28  WSN  Third Baseman    136  529   88
16   1214       Martin Prado  2016   32  MIA  Third Baseman    153  600   70
17   1266        Kris Bryant  2017   25  CHC  Third Baseman    151  549  111
18   1325     Mike Moustakas  2018   29  TOT  Third Baseman    152  573   66
19   1326     Mike Moustakas  2018   29  KCR  Third Baseman     98  378   46
20   1444     Matt Carpenter  2016   30  STL  Third Baseman    129  473   81
21   1445     Matt Carpenter  2017   31  STL  Third Baseman    145  497   91
22   1446     Matt Carpenter  2018   32  STL  Third Baseman    156  564  111
23   1526     Eugenio Suarez  2018   26  CIN  Third Baseman    143  527   79
24   1573       David Freese  2017   34  PIT  Third Baseman    130  426   44
25   1596      Justin Turner  2016   31  LAD  Third Baseman    151  556   79
26   1597      Justin Turner  2017   32  LAD  Third Baseman    130  457   72
27   1598      Justin Turner  2018   33  LAD  Third Baseman    103  365   62
28   1645    Eduardo Escobar  2018   29  TOT  Third Baseman    151  566   75
29   1646    Eduardo Escobar  2018   29  MIN  Third Baseman     97  368   45
30   1727      Manny Machado  2016   23  BAL  Third Baseman    157  640  105
31   1728      Manny Machado  2017   24  BAL  Third Baseman    156  630   81
32   1729      Manny Machado  2018   25  TOT  Third Baseman    162  632   84
33   1730      Manny Machado  2018   25  BAL  Third Baseman     96  365   48
34   1731      Manny Machado  2018   25  LAD  Third Baseman     66  267   36
35   1766      Nolan Arenado  2016   25  COL  Third Baseman    160  618  116
36   1767      Nolan Arenado  2017   26  COL  Third Baseman    159  606  100
37   1768      Nolan Arenado  2018   27  COL  Third Baseman    156  590  104
38   1866      Evan Longoria  2016   30  TBR  Third Baseman    160  633   81
39   1867      Evan Longoria  2017   31  TBR  Third Baseman    156  613   71

      H     ...          SB %   BB   SO        BA    OBP    SLG    OPS  WAR  \
0   192     ...      0.611111   66   80  0.347826  0.416  0.495  0.911  5.3
1   189     ...      0.545455   59   90  0.310345  0.374  0.409  0.783  2.8
2   147     ...      0.545455   37   82  0.275797  0.321  0.428  0.749  3.0
3   121     ...      0.875000   41  138  0.259657  0.325  0.384  0.709  2.7
4   186     ...      0.772727   52   69  0.317949  0.374  0.583  0.957  6.9
5   156     ...      0.850000  106   80  0.269896  0.387  0.552  0.939  7.9
6   132     ...      0.750000   28   90  0.271605  0.339  0.432  0.771  3.4
7   158     ...      1.000000   87  138  0.262895  0.357  0.529  0.886  3.8
8   143     ...      1.000000  104  133  0.258123  0.377  0.504  0.881  2.8
9   164     ...      0.875000  109  119  0.284229  0.404  0.549  0.953  7.6
10  112     ...      0.500000   76  111  0.269880  0.385  0.559  0.944  5.0
11  133     ...      0.750000   64  163  0.225424  0.302  0.464  0.766  3.2
12  101     ...      0.571429   83  125  0.213080  0.344  0.428  0.772  3.4
13  153     ...      0.666667   65  117  0.269841  0.348  0.450  0.798  3.9
14  153     ...      0.777778   84   82  0.301181  0.403  0.533  0.936  5.9
15  163     ...      0.666667   55   82  0.308129  0.374  0.535  0.909  4.2
16  183     ...      0.500000   49   69  0.305000  0.359  0.417  0.776  3.9
17  162     ...      0.583333   95  128  0.295082  0.409  0.537  0.946  6.1
18  144     ...      0.800000   49  103  0.251309  0.315  0.459  0.774  2.5
19   94     ...      1.000000   30   63  0.248677  0.309  0.468  0.777  2.1
20  128     ...      0.000000   81  108  0.270613  0.380  0.505  0.885  3.5
21  120     ...      0.666667  109  125  0.241449  0.384  0.451  0.835  2.9
22  145     ...      0.800000  102  158  0.257092  0.374  0.523  0.897  4.9
23  149     ...      0.500000   64  142  0.282732  0.366  0.526  0.892  4.2
24  112     ...      0.000000   58  116  0.262911  0.368  0.371  0.739  2.1
25  153     ...      0.800000   48  107  0.275180  0.339  0.493  0.832  4.7
26  147     ...      0.875000   59   56  0.321663  0.415  0.530  0.945  5.8
27  114     ...      0.666667   47   54  0.312329  0.406  0.518  0.924  4.5
28  154     ...      0.333333   52  126  0.272085  0.334  0.489  0.823  3.2
29  101     ...      0.250000   34   91  0.274457  0.338  0.514  0.852  2.2
30  188     ...      0.000000   48  120  0.293750  0.343  0.533  0.876  6.9
31  163     ...      0.692308   50  115  0.258730  0.310  0.471  0.781  3.5
32  188     ...      0.875000   70  104  0.297468  0.367  0.538  0.905  5.7
33  115     ...      0.888889   45   51  0.315068  0.387  0.575  0.962  2.9
34   73     ...      0.857143   25   53  0.273408  0.338  0.487  0.825  2.8
35  182     ...      0.400000   68  103  0.294498  0.362  0.570  0.932  6.6
36  187     ...      0.600000   62  106  0.308581  0.373  0.586  0.959  7.1
37  175     ...      0.500000   73  122  0.296610  0.374  0.561  0.935  5.6
38  173     ...      0.000000   42  144  0.273302  0.318  0.521  0.839  3.9
39  160     ...      0.857143   46  109  0.261011  0.313  0.424  0.737  3.4

      Salary  Adj Salary
0    3000000     3115592
1    4800000     4750662
2    8500000     8500000
3    2550000     2550000
4    2571400     2544969
5    2428600     2428600
6    7500000     7422909
7   10000000    10385307
8   18150000    17963439
9   11650000    12098882
10  17000000    16825259
11   7500000     7788980
12  12000000    11876654
13   2800000     2907886
14   5800000     5740383
15  12300000    12300000
16  14000000    14539429
17   1050000     1039207
18   7700000     7700000
19   3577950     3577950
20   6250000     6490817
21   9750000     9649781
22  13500000    13500000
23   4250000     4250000
24   6250000     6185757
25   5100000     5296506
26  16000000    15835538
27  11000000    11000000
28   3389750     3389750
29   1694875     1694875
30   5000000     5192653
31  11500000    11381793
32  16000000    16000000
33   9634408     9634408
34   6365592     6365592
35   5000000     5192653
36  11750000    11629223
37  17272850    17272850
38  12100000    12566221
39  11525000    11406536

[40 rows x 26 columns]

In [63]:
sql_query = 'SELECT * FROM Hitters WHERE Position = "Outfielder" AND Year > 2015 AND WAR > 2 AND Salary > 1000000'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

    index                Player  Year  Age Team    Position  Games   AB    R  \
0      60          Mookie Betts  2018   25  BOS  Outfielder    136  520  129
1      65     Jackie Bradley Jr  2017   27  BOS  Outfielder    133  482   58
2      66     Jackie Bradley Jr  2018   28  BOS  Outfielder     34  474   76
3      73           JD Martinez  2017   29  TOT  Outfielder    119  432   85
4      75           JD Martinez  2017   29  ARI  Outfielder     62  232   47
5      76           JD Martinez  2018   30  BOS  Outfielder    150  569  111
6     104           Aaron Hicks  2017   27  NYY  Outfielder     88  301   54
7     105           Aaron Hicks  2018   28  NYY  Outfielder    137  480   90
8     114         Brett Gardner  2016   32  NYY  Outfielder    148  547   80
9     115         Brett Gardner  2017   33  NYY  Outfielder    151  594   96
10    116         Brett Gardner  2018   34  NYY  Outfielder    140  530   95
11    141     Giancarlo Stanton  2016   26  MIA  Outfielder    119  413   56
12    142     Giancarlo Stanton  2017   27  MIA  Outfielder    159  597  123
13    143     Giancarlo Stanton  2018   28  NYY  Outfielder    158  617  102
14    164        Avisail Garcia  2017   26  CHW  Outfielder    136  518   75
15    172       Kevin Kiermaier  2017   27  TBR  Outfielder     98  380   56
16    173       Kevin Kiermaier  2018   28  TBR  Outfielder     88  332   44
17    253        Randal Grichuk  2018   26  TOR  Outfielder    124  424   60
18    299       Carlos Gonzalez  2016   30  COL  Outfielder    150  584   87
19    399  Nicholas Castellanos  2018   26  DET  Outfielder    157  620   88
20    457           Nelson Cruz  2016   35  SEA  Outfielder    155  589   96
21    458           Nelson Cruz  2017   36  SEA  Outfielder    155  556   91
22    459           Nelson Cruz  2018   37  SEA  Outfielder    144  519   70
23    505           Alex Gordon  2018   34  KCR  Outfielder    141  506   56
24    555      Michael Brantley  2017   30  CLE  Outfielder     90  338   47
25    556      Michael Brantley  2018   31  CLE  Outfielder    143  570   89
26    574          Josh Reddick  2016   29  TOT  Outfielder    115  398   53
27    575          Josh Reddick  2016   29  OAK  Outfielder     68  243   33
28    577          Josh Reddick  2017   30  HOU  Outfielder    134  477   77
29    582       George Springer  2017   27  HOU  Outfielder    140  548  112
..    ...                   ...   ...  ...  ...         ...    ...  ...  ...
46    932      Andrew McCutchen  2018   31  TOT  Outfielder    155  569   83
47   1015         Nick Markakis  2018   34  ATL  Outfielder     45  623   78
48   1161            Adam Eaton  2016   27  CHW  Outfielder    157  619   91
49   1245     Curtis Granderson  2016   35  NYM  Outfielder    150  545   88
50   1299         Jason Heyward  2017   27  CHC  Outfielder    126  432   59
51   1350            Ryan Braun  2016   32  MIL  Outfielder    135  511   80
52   1357          Lorenzo Cain  2016   30  KCR  Outfielder    103  397   56
53   1358          Lorenzo Cain  2017   31  KCR  Outfielder    155  584   86
54   1359          Lorenzo Cain  2018   32  MIL  Outfielder    141  539   90
55   1368      Christian Yelich  2017   25  MIA  Outfielder    156  602  100
56   1369      Christian Yelich  2018   26  MIL  Outfielder    147  574  118
57   1399         Melky Cabrera  2016   31  CHW  Outfielder    151  591   70
58   1408        Starling Marte  2016   27  PIT  Outfielder    129  489   71
59   1410        Starling Marte  2018   29  PIT  Outfielder    145  559   81
60   1479         Dexter Fowler  2016   30  CHC  Outfielder    125  456   84
61   1489         Marcell Ozuna  2017   26  MIA  Outfielder    159  613   93
62   1490         Marcell Ozuna  2018   27  STL  Outfielder    148  582   69
63   1543           Yasiel Puig  2017   26  LAD  Outfielder    152  499   72
64   1544           Yasiel Puig  2018   27  LAD  Outfielder    125  405   60
65   1605     Enrique Hernandez  2018   26  LAD  Outfielder    145  402   67
66   1609          Joc Pederson  2018   26  LAD  Outfielder    148  395   65
67   1666          Jarrod Dyson  2016   31  KCR  Outfielder    107  299   46
68   1667          Jarrod Dyson  2017   32  SEA  Outfielder    111  346   56
69   1680            Adam Jones  2017   31  BAL  Outfielder    147  597   82
70   1686         David Peralta  2018   30  ARI  Outfielder    146  560   75
71   1742            Will Myers  2018   27  SDP  Outfielder     83  312   39
72   1804      Charlie Blackmon  2016   29  COL  Outfielder    143  578  111
73   1805      Charlie Blackmon  2017   30  COL  Outfielder    159  644  137
74   1816           Ian Desmond  2016   30  TEX  Outfielder    156  625  107
75   1892          Kevin Pillar  2018   29  TOR  Outfielder    142  512   65

      H     ...          SB %  BB   SO        BA    OBP    SLG    OPS   WAR  \
0   180     ...      0.833333  81   91  0.346154  0.438  0.640  1.078  10.9
1   118     ...      0.727273  48  124  0.244813  0.323  0.402  0.725   3.0
2   111     ...      0.944444  46  137  0.234177  0.314  0.403  0.717   2.1
3   131     ...      1.000000  53  128  0.303241  0.376  0.690  1.066   4.2
4    70     ...      1.000000  24   74  0.301724  0.366  0.741  1.107   2.6
5   188     ...      0.857143  69  146  0.330404  0.402  0.629  1.031   6.4
6    80     ...      0.666667  51   67  0.265781  0.372  0.475  0.847   3.9
7   119     ...      0.846154  90  111  0.247917  0.366  0.467  0.833   4.7
8   143     ...      0.800000  70  106  0.261426  0.351  0.362  0.713   3.4
9   157     ...      0.821429  72  122  0.264310  0.350  0.428  0.778   4.9
10  125     ...      0.888889  65  107  0.235849  0.322  0.368  0.690   2.8
11   99     ...      0.000000  50  140  0.239709  0.326  0.489  0.815   2.6
12  168     ...      0.500000  85  163  0.281407  0.376  0.631  1.007   7.9
13  164     ...      1.000000  70  211  0.265802  0.343  0.509  0.852   4.0
14  171     ...      0.500000  33  111  0.330116  0.380  0.506  0.886   4.6
15  105     ...      0.695652  31   99  0.276316  0.338  0.450  0.788   5.0
16   72     ...      0.666667  25   91  0.216867  0.282  0.370  0.652   2.5
17  104     ...      0.600000  27  122  0.245283  0.301  0.502  0.803   2.2
18  174     ...      0.500000  46  129  0.297945  0.350  0.505  0.855   2.4
19  185     ...      0.666667  49  151  0.298387  0.354  0.500  0.854   2.9
20  169     ...      1.000000  62  159  0.286927  0.360  0.555  0.915   4.7
21  160     ...      0.500000  70  140  0.287770  0.375  0.549  0.924   4.3
22  133     ...      1.000000  55  122  0.256262  0.342  0.509  0.851   2.9
23  124     ...      0.857143  50  124  0.245059  0.324  0.370  0.694   2.4
24  101     ...      0.916667  31   50  0.298817  0.357  0.444  0.801   2.1
25  176     ...      0.800000  48   60  0.308772  0.364  0.468  0.832   3.6
26  112     ...      0.727273  39   56  0.281407  0.345  0.405  0.750   2.5
27   72     ...      1.000000  28   34  0.296296  0.368  0.449  0.817   2.3
28  150     ...      0.700000  43   72  0.314465  0.363  0.484  0.847   4.1
29  155     ...      0.416667  64  111  0.282847  0.367  0.522  0.889   4.7
..  ...     ...           ...  ..  ...       ...    ...    ...    ...   ...
46  145     ...      0.608696  95  145  0.254833  0.368  0.424  0.792   2.8
47  185     ...      0.500000  72   80  0.296950  0.366  0.440  0.806   2.6
48  176     ...      0.736842  63  115  0.284330  0.362  0.428  0.790   6.1
49  129     ...      0.666667  74  130  0.236697  0.335  0.464  0.799   2.8
50  112     ...      0.500000  41   67  0.259259  0.326  0.389  0.715   2.2
51  156     ...      0.761905  46   98  0.305284  0.365  0.538  0.903   4.4
52  114     ...      0.736842  31   84  0.287154  0.339  0.408  0.747   3.0
53  175     ...      0.928571  54  100  0.299658  0.363  0.440  0.803   5.4
54  166     ...      0.810811  71   94  0.307978  0.395  0.417  0.812   6.9
55  170     ...      0.888889  80  137  0.282392  0.369  0.439  0.808   4.2
56  187     ...      0.846154  68  135  0.325784  0.402  0.598  1.000   7.6
57  175     ...      1.000000  47   69  0.296108  0.345  0.455  0.800   2.5
58  152     ...      0.796610  23  104  0.310838  0.362  0.456  0.818   4.9
59  155     ...      0.702128  35  109  0.277281  0.327  0.460  0.787   3.7
60  126     ...      0.764706  79  124  0.276316  0.393  0.447  0.840   4.1
61  191     ...      0.250000  64  144  0.311582  0.376  0.548  0.924   6.1
62  163     ...      1.000000  38  110  0.280069  0.325  0.433  0.758   2.9
63  131     ...      0.714286  64  100  0.262525  0.346  0.487  0.833   3.8
64  108     ...      0.750000  36   87  0.266667  0.327  0.494  0.821   2.7
65  103     ...      1.000000  50   78  0.256219  0.336  0.470  0.806   3.2
66   98     ...      0.166667  40   85  0.248101  0.321  0.522  0.843   2.3
67   83     ...      0.810811  26   39  0.277592  0.340  0.388  0.728   3.2
68   87     ...      0.800000  28   55  0.251445  0.324  0.350  0.674   2.7
69  170     ...      0.666667  27  113  0.284757  0.322  0.466  0.788   2.6
70  164     ...      1.000000  48  124  0.292857  0.352  0.516  0.868   3.9
71   79     ...      0.928571  30   94  0.253205  0.318  0.446  0.764   2.4
72  187     ...      0.653846  43  102  0.323529  0.381  0.552  0.933   4.5
73  213     ...      0.583333  65  135  0.330745  0.399  0.601  1.000   5.9
74  178     ...      0.777778  44  160  0.284800  0.335  0.446  0.781   2.7
75  129     ...      0.823529  18   98  0.251953  0.282  0.426  0.708   2.5

      Salary  Adj Salary
0   10500000    10500000
1    3600000     3562996
2    6100000     6100000
3   11750000    11629223
4    4879808     4829649
5   23750000    23750000
6    1350000     1336124
7    1825000     1825000
8   13000000    13500899
9   12000000    11876654
10  11000000    11000000
11   9000000     9346776
12  14500000    14350957
13  25000000    25000000
14   3000000     2969163
15   4000000     3958885
16   5500000     5500000
17   2800000     2800000
18  17050000    17706948
19   6050000     6050000
20  14000000    14539429
21  14000000    13856096
22  14025000    14025000
23  20000000    20000000
24   7500000     7422909
25  12000000    12000000
26   6575000     6828339
27   4311476     4477600
28  13000000    12866375
29   3900000     3859912
..       ...         ...
46  14750000    14750000
47  10550000    10550000
48   2750000     2855959
49  16000000    16616491
50  21500000    21279005
51  20000000    20770613
52   6500000     6750449
53  11000000    10886933
54  13300000    13300000
55   3500000     3464024
56   7000000     7000000
57  14000000    14539429
58   3000000     3115592
59   7500000     7500000
60   8000000     8308245
61   3500000     3464024
62   9000000     9000000
63   6500000     6433187
64   7419354     7419354
65   1600000     1600000
66   2600000     2600000
67   1725000     1791465
68   2800000     2771219
69  16000000    15835538
70   3300000     3300000
71   2000000     2000000
72   3500000     3634857
73   7300000     7224964
74   8000000     8308245
75   3250000     3250000

[76 rows x 26 columns]

In [56]:
sql_query = 'SELECT AVG(BA) FROM Hitters WHERE (Player = "Kurt Suzuki" OR Player = "Anthony Rizzo" OR Player = "Brian Dozier" OR Player = "DJ Lemahieu" OR Player = "Jean Segura" OR Player = "Charlie Blackmon" OR Player = "Christian Yelich" OR Player = "David Peralta" OR Player = "Chris Iannetta" OR Player = "Eduardo Escobar" OR Player = "Steve Pearce" OR Player = "Kevin Pillar") AND Year = 2018'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

   AVG(BA)
0  0.26727

In [58]:
sql_query = 'SELECT SUM(HR) FROM Hitters WHERE (Player = "Kurt Suzuki" OR Player = "Anthony Rizzo" OR Player = "Brian Dozier" OR Player = "DJ Lemahieu" OR Player = "Jean Segura" OR Player = "Charlie Blackmon" OR Player = "Christian Yelich" OR Player = "David Peralta" OR Player = "Chris Iannetta" OR Player = "Eduardo Escobar" OR Player = "Steve Pearce" OR Player = "Kevin Pillar") AND Year = 2018'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

   SUM(HR)
0      293

In [60]:
sql_query = 'SELECT SUM(R) FROM Hitters WHERE (Player = "Kurt Suzuki" OR Player = "Anthony Rizzo" OR Player = "Brian Dozier" OR Player = "DJ Lemahieu" OR Player = "Jean Segura" OR Player = "Charlie Blackmon" OR Player = "Christian Yelich" OR Player = "David Peralta" OR Player = "Chris Iannetta" OR Player = "Eduardo Escobar" OR Player = "Steve Pearce" OR Player = "Kevin Pillar") AND Year = 2018'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

   SUM(R)
0    1095

In [61]:
sql_query = 'SELECT SUM(BB) FROM Hitters WHERE (Player = "Kurt Suzuki" OR Player = "Anthony Rizzo" OR Player = "Brian Dozier" OR Player = "DJ Lemahieu" OR Player = "Jean Segura" OR Player = "Charlie Blackmon" OR Player = "Christian Yelich" OR Player = "David Peralta" OR Player = "Chris Iannetta" OR Player = "Eduardo Escobar" OR Player = "Steve Pearce" OR Player = "Kevin Pillar") AND Year = 2018'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

   SUM(BB)
0      706

In [62]:
sql_query = 'SELECT SUM(SO) FROM Hitters WHERE (Player = "Kurt Suzuki" OR Player = "Anthony Rizzo" OR Player = "Brian Dozier" OR Player = "DJ Lemahieu" OR Player = "Jean Segura" OR Player = "Charlie Blackmon" OR Player = "Christian Yelich" OR Player = "David Peralta" OR Player = "Chris Iannetta" OR Player = "Eduardo Escobar" OR Player = "Steve Pearce" OR Player = "Kevin Pillar") AND Year = 2018'
Hitters_Data = pd.read_sql(sql_query, conn)
print(Hitters_Data)

   SUM(SO)
0     1444